_maps/map_files/AAA_Outpost/DisalaraOutpost.dmm
Did a lot of stuff. Made outdoors nicer, made the inside look rundown, added stuff to rooms, created rooms, pending further changes until I know what to do with other spots. I did not test but all I did was add junk so if anything broke then eat me. Pls do a looksie or ask me to stream to make sure it's what is wanted.
=> First Z Stuff

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> teehee I can't stop mapping

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
tested nothing, hoped for everything.
=> Updated map to add atmospherics, added in the stuff I missed.

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> telecomms, disposals fix, cyborg/AI room

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
…ere were four stacked oops)
she dragon on my dogma until I arisen
=> bar addition, move science desk, remove some posters from science (th

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
disposals system fixed potentially, a few APCs were not connected to power wires (kitchen and cargo), stray tiling, area refining
also reminding you cutely to disable the random stray cargo pod event.
=> misc armpit fixes see desc

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
cargo redone, hydroponics moved, disposals attempted again, workshop added to science, path added outside hanger, telecomms floor in robotics temperature fix
=> many changes

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> I hate disposals

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> button and sinks

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> button, sinks, spawns

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> fixed vent directions after they were randomized

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
add navigation beacons and the engineering lathe
=> bot patrol routes

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> atmos valve, add cute decorations

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
down the drain
https://www.youtube.com/watch?v=XrSXLYU85N4
=> drains drains drains

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> fix console, minor layout fix

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> plates and service lathe

_maps/map_files/SuzerainNokura/SuzerainNokura.dmm
=> removing weird hybrid of two map updates

code/modules/mob/living/basic/trooper/trooper.dm, modular_nova/modules/ices_events/code/ICES_event_config.dm
=> turns off scrubber overflow

modular_nova/modules/ices_events/code/ICES_event_config.dm
=> ACTUALLY disables overflow now

code/__DEFINES/time.dm, code/controllers/subsystem/ticker.dm, code/modules/client/preferences.dm, code/modules/jobs/job_types/chief_engineer.dm, code/modules/jobs/job_types/chief_medical_officer.dm, code/modules/jobs/job_types/medical_doctor.dm, code/modules/jobs/job_types/prisoner.dm, code/modules/jobs/job_types/quartermaster.dm, code/modules/jobs/job_types/research_director.dm, code/modules/jobs/job_types/scientist.dm, modular_warrenstation/code/modules/jobs.dm, tgstation.dme
=> time + job changes

_maps/map_files/Mining/Lavaland.dmm, modular_nova/modules/advanced_shuttles/code/shuttles.dm, modular_nova/modules/emotes/code/emotes.dm
=> attempt fix at mining

_maps/map_files/generic/CentCom_nova_z2.dmm
=> Telecomms!

_maps/map_files/generic/CentCom_nova_z2.dmm
=> add one wire, update medical lathe (hopefully fix?)

modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_tumor.dm
<details>
<summary>Screenshots/Videos</summary>
</details>
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> slightly reduced hemophage blood drain

_maps/map_files/generic/CentCom_nova_z2.dmm
=> make ship more pretty

code/controllers/subsystem/library.dm
=> disables library loading because it takes 817 seconds to load it

_maps/map_files/generic/CentCom_nova_z2.dmm
=> REEEE NO APC

tgui/packages/tgui/styles/colors.scss, tgui/packages/tgui/styles/themes/ntos.scss
=> jaeger-fies the TG-UI

modular_warrenstation/money_rework/code/money.dm, modular_warrenstation/money_rework/code/moneyspawners.dm, tgstation.dme
Requested port, adds more money changes from Lethalstation
-PR Could not be fully tested due to mapgen issues affecting game launch.
-Code builds correctly with no issues
Requested port.
:cl: Koltsov
code: Miscellaneous fixes, had to bring in newer money.dm code from lethalstation
/:cl:
=> Ports More Money Changes

modular_warrenstation/mobs/lethalmobs.dm, modular_warrenstation/mobs/mob_ai.dm, modular_warrenstation/mobs/mob_dsword.dm, modular_warrenstation/mobs/moboutfits.dm, tgstation.dme
Requested port, adds lethalmobs from Lethalstation
-PR Could not be fully tested due to mapgen issues affecting game launch.
-Code builds correctly with no issues
Requested port.
:cl: Koltsov
add: Adds lethalmobs to code
/:cl:
=> Ports Lethalmobs

config/nova/title_html.txt
=> an attempt at titlehtml

code/modules/vending/youtool.dm, modular_warrenstation/deepmaint_stuff/code/order_console_slop/order_console.dm
=> console change plus vending machine

code/modules/holiday/holidays.dm
=> holiday changes

modular_warrenstation/code/datums/quirks/neutral_quirks/waddle.dm, tgstation.dme
Requested port, adds the waddle quirk from Bubberstation
-PR Could not be fully tested due to mapgen issues affecting game launch.
-Code builds correctly with no issues
Requested port.
:cl: Koltsov
adds: New Quirk: Waddle
/:cl:
=> Ports Waddle Quirk

code/datums/ai_laws/ai_laws.dm, code/datums/ai_laws/laws_station_sided.dm
Requested by bunny
no I will not describe the pull request since its unnecessary given the contents
It doesnt contribute to the nova sector roleplay experience because this is warren station
I dunno they probably make cyborgs happy
I will provide no proof of testing (Because I didnt test it)
<details>
<summary>Screenshots/Videos</summary>
</details>
:cl:
balance: removed cyborg laws
/:cl:
=> No more laws for cyborgs

config/config.txt
See title
Reduces the respawn timer
This isnt nova sector
I did not test this change because it isnt capable of being tested on my machine
<details>
<summary>Screenshots/Videos</summary>
</details>
:cl:
qol: made respawn timer 20 seconds
/:cl:
=> Reduces respawn timer to 20 seconds

_maps/map_files/generic/CentCom_nova_z2.dmm
=> suzie love

_maps/map_files/generic/CentCom_nova_z2.dmm
=> literally just one added wire

_maps/map_files/generic/CentCom_nova_z2.dmm, _maps/shuttles/nova/cargo_nova.dmm, tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx
=> unatomized mega PR number fourty
